export enum UserProxies {
	CREATE = 'PROXY_CREATE_USER',
	FIND = 'PROXY_FIND_USER',
	FIND_BY_CRITERIA = 'PROXY_FIND_USERS_BY_CRITERIA',
	FIND_RAW_BY_OPTIONS = 'PROXY_FIND_RAW_USER_BY_OPTIONS',
	UPDATE = 'PROXY_UPDATE_USER',
	SOFT_DELETE = 'PROXY_SOFT_DELETE_USER',
}
